// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlCOFQ3pU-DXWG8n8TrpHSbVrKv3tsv1o',
    appId: '1:829712973332:web:9dc3cef754a78f66fdf101',
    messagingSenderId: '829712973332',
    projectId: 'fir-practices-e3f4d',
    authDomain: 'fir-practices-e3f4d.firebaseapp.com',
    databaseURL: 'https://fir-practices-e3f4d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-practices-e3f4d.appspot.com',
    measurementId: 'G-NS6BTVL1V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKeJvO_on3bqjCAJfDKdTLzgJJ1AuqtZg',
    appId: '1:829712973332:android:691f61242e297894fdf101',
    messagingSenderId: '829712973332',
    projectId: 'fir-practices-e3f4d',
    databaseURL: 'https://fir-practices-e3f4d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-practices-e3f4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClQiwW3J7nwU4v9eOa54krWZAn_ixONaI',
    appId: '1:829712973332:ios:70bf1d01e87acbe4fdf101',
    messagingSenderId: '829712973332',
    projectId: 'fir-practices-e3f4d',
    databaseURL: 'https://fir-practices-e3f4d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-practices-e3f4d.appspot.com',
    androidClientId: '829712973332-ah1h5cmnit3cj6ldjh9pq388dih8soc4.apps.googleusercontent.com',
    iosClientId: '829712973332-mfj0uoulhjel0a33i1aed1sgeg04918h.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiiesAttendanceApp',
  );
}
